import {
    HorizontalBox,
    VerticalBox,
    Button,
    StyleMetrics,
    GridBox,
    GroupBox,
    Switch,
    ComboBox,
    LineEdit,
} from "std-widgets.slint";
import { Style, Colors } from "../styles.slint";
import { PlotSize } from "../size.slint";
import {
    UiTrainingState,
    UiPlotRangeType,
    Actions,
    Formatters,
    Plots,
} from "../globals.slint";

component StatWidget inherits Rectangle {
    in property <string> name;
    in property <string> value;

    HorizontalBox {
        padding: 0;
        padding-bottom: 8px;
        alignment: space-between;

        Text {
            text: name;
            color: gray;
        }

        Text {
            text: value.is-empty ? "N/A" : value;
        }
    }
}

component Toggle inherits Rectangle {
    in property <string> label;
    in-out property <bool> is-on;

    HorizontalLayout {
        alignment: space-between;
        Text {
            text: label;
            color: gray;
        }

        Switch {
            checked: is-on;
            toggled => {
                root.is-on = self.checked;
            }
        }
    }
}

component PlotsRangeSettings inherits Rectangle {
    in-out property <UiPlotRangeType> range-type <=> Plots.range-type;
    in-out property <int> last-epochs <=> Plots.last-epochs;
    in-out property <int> range-start <=> Plots.custom-range-start;
    in-out property <int> range-end <=> Plots.custom-range-end;
    property <string> last-epochs-string: last-epochs;
    property <string> range-start-string: range-start;
    property <string> range-end-string: range-end;

    VerticalLayout {
        spacing: 8px;
        alignment: start;
        Text {
            text: "range:";
            color: gray;
            vertical-alignment: center;
        }

        ComboBox {
            model: ["all", "last", "custom"];
            selected(current-value) => {
                range-type = range-type-from-string(current-value);
                Plots.range-settings-changed();
            }
        }

        if (range-type == UiPlotRangeType.last-epochs):
            LineEdit {
            placeholder-text: "number of epochs";
            input-type: number;
            text: last-epochs-string;
            accepted(text) => {
                last-epochs = text.to-float();
                Plots.range-settings-changed();
            }
        }

        if (range-type == UiPlotRangeType.custom):
        VerticalLayout {
            LineEdit {
                placeholder-text: "epochs from";
                text: range-start-string;
                accepted(text) => {
                    range-start = text.to-float();
                    Plots.range-settings-changed();
                }
            }

            LineEdit {
                placeholder-text: "epochs to";
                text: range-end-string;
                accepted(text) => {
                    range-end = text.to-float();
                    Plots.range-settings-changed();
                }
            }
        }
    }

    function range-type-from-string(type: string) -> UiPlotRangeType {
        if (type == "custom") {
            return UiPlotRangeType.custom;
        } else if (type == "last") {
            return UiPlotRangeType.last-epochs;
        } else {
            return UiPlotRangeType.all;
        }
    }
}

export component TrainingWidget inherits Rectangle {
    in property <UiTrainingState> state;
    in property <int> epoch;
    in property <int> epochs-per-second;
    in property <int> best-score;
    in property <int> best-tile;
    in property <int> recorded-transitions;
    in property <float> epsilon;
    in property <image> score-plot;
    in property <image> epoch-length-plot;
    in property <image> reward-plot;
    in property <image> best-tile-plot;
    out property <PlotSize> plots-area-size: { width: plots-area.width / 1px, height: plots-area.height / 1px };

    min-width: 1000px;
    min-height: 600px;
    HorizontalBox {
        padding-top: 0;
        plots-area := GridBox {
            spacing: Style.plots-spacing;

            Rectangle {
                row: 0;
                col: 0;
                rowspan: 1;
                colspan: 1;

                border-radius: Style.corner-radius;
                background: Colors.game-background;

                score-plot-image := Image {
                    source: score-plot;
                    width: 100%;
                    height: 100%;
                }
            }

            Rectangle {
                row: 0;
                col: 1;
                rowspan: 1;
                colspan: 1;

                border-radius: Style.corner-radius;
                background: Colors.game-background;

                epoch-length-plot-image := Image {
                    source: epoch-length-plot;
                    width: 100%;
                    height: 100%;
                }
            }

            Rectangle {
                row: 1;
                col: 0;
                rowspan: 1;
                colspan: 1;
                border-radius: Style.corner-radius;
                background: Colors.game-background;

                reward-plot-image := Image {
                    source: reward-plot;
                    width: 100%;
                    height: 100%;
                }
            }

            Rectangle {
                row: 1;
                col: 1;
                rowspan: 1;
                colspan: 1;
                border-radius: Style.corner-radius;
                background: Colors.game-background;

                best-tile-plot-image := Image {
                    source: best-tile-plot;
                    width: 100%;
                    height: 100%;
                }
            }
        }

        VerticalBox {
            padding-top: 0;
            padding-left: 0;
            width: 200px;

            VerticalLayout {
                alignment: start;
                spacing: 8px;
                GroupBox {
                    title: "stats";
                    VerticalLayout {
                        alignment: start;
                        StatWidget {
                            name: "state";
                            value: training-state-string(state);
                        }

                        StatWidget {
                            name: "epoch";
                            value: Formatters.format-int(epoch);
                        }

                        StatWidget {
                            name: "epochs/s";
                            value: epochs-per-second;
                        }

                        StatWidget {
                            name: "best score";
                            value: Formatters.format-int(best-score);
                        }

                        StatWidget {
                            name: "best tile";
                            value: best-tile;
                        }

                        StatWidget {
                            name: "recorded moves";
                            value: Formatters.format-int(recorded-transitions);
                        }

                        StatWidget {
                            name: "epsilon";
                            value: epsilon.to-fixed(5);
                        }
                    }
                }

                GroupBox {
                    title: "plots";
                    VerticalLayout {
                        alignment: start;
                        spacing: 8px;

                        //                        Toggle {
//                            label: "log scale";
//                            is-on: Plots.log-scale;
//                            changed is-on => {
//                                Plots.log-scale = self.is-on;
//                                Plots.range-settings-changed();
//                            }
//                        }

                        PlotsRangeSettings { }
                    }
                }
            }

            Rectangle { }

            Button {
                text: root.state == UiTrainingState.idle ? "start" : "pause";
                clicked => {
                    if (root.state == UiTrainingState.idle) {
                        Actions.start-training();
                    } else {
                        Actions.pause-training();
                    }
                }
            }
        }
    }

    function training-state-string(state: UiTrainingState) -> string {
        return state == UiTrainingState.idle ? "idle" : state == UiTrainingState.training ? "training" : "unknown";
    }
}
