import { HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Style, Colors } from "../styles.slint";

component StatWidget inherits Rectangle {
    in property <string> name;
    in property <string> value;

    HorizontalBox {
        alignment: space-between;

        Text {
            text: name;
            color: gray;
        }

        Text {
            text: value;
        }
    }
}

export enum TrainingState { idle, training }

export struct Size {
    width: int,
    height: int,
}

export component TrainingWidget inherits Rectangle {
    in property <TrainingState> state;
    in property <int> epoch;
    in property <float> epochs-per-second;
    in property <int> best-score;
    in property <image> plot;
    out property <Size> plot-size: { width: image.width / 1px, height: image.height / 1px };

    HorizontalBox {
        Rectangle {
            min-width: 600px;
            min-height: 400px;
            border-radius: Style.corner-radius;
            background: Colors.game-background;

            image := Image {
                source: plot;
                width: 100%;
                height: 100%;
            }
        }

        VerticalBox {
            alignment: end;

            StatWidget {
                name: "state";
                value: training-state-string(state);
            }

            StatWidget {
                name: "epoch";
                value: epoch;
            }

            StatWidget {
                name: "epochs/s";
                value: epochs-per-second;
            }

            StatWidget {
                name: "best score";
                value: best-score;
            }
        }
    }

    function training-state-string(state: TrainingState) -> string {
        return state == TrainingState.idle ? "idle" : state == TrainingState.training ? "training" : "unknown";
    }
}
