import { Style, Colors } from "../styles.slint";
import { Tile, TileData } from "tile.slint";

component TileSlot inherits Rectangle {
    width: Style.tile-size;
    height: Style.tile-size;
    background: Colors.empty-tile;
    border-radius: Style.corner-radius;
}

component GameBoardBackground inherits GridLayout {
    padding-top: Style.margin;
    padding-left: Style.margin;
    spacing: Style.margin;

    Row {
        TileSlot { }

        TileSlot { }

        TileSlot { }

        TileSlot { }
    }

    Row {
        TileSlot { }

        TileSlot { }

        TileSlot { }

        TileSlot { }
    }

    Row {
        TileSlot { }

        TileSlot { }

        TileSlot { }

        TileSlot { }
    }

    Row {
        TileSlot { }

        TileSlot { }

        TileSlot { }

        TileSlot { }
    }
}

export component GameBoard inherits Rectangle {
    width: 2 * Style.margin + 4 * Style.tile-size + 3 * Style.margin;
    height: 2 * Style.margin + 4 * Style.tile-size + 3 * Style.margin;
    background: Colors.game-background;
    border-radius: Style.corner-radius;

    in-out property <[TileData]> tiles: [{ value: 2, row: 0, column: 0, just-appeared: false },
        // { value: 4, row: 0, column: 2 },
        // { value: 8, row: 0, column: 3 },
        // { value: 16, row: 1, column: 0 },
        // { value: 32, row: 1, column: 1 },
        // { value: 64, row: 1, column: 2 },
        // { value: 128, row: 1, column: 3 },
        // { value: 256, row: 2, column: 0 },
        // { value: 512, row: 2, column: 1 },
        // { value: 1024, row: 2, column: 2 },
        // { value: 2048, row: 2, column: 3 },
    ];

    forward-focus: key-handler;
    key-handler := FocusScope {
        key-pressed(event) => {
            if (event.text == Key.LeftArrow) {
                tiles[0].column = 0;
            }
            if (event.text == Key.RightArrow) {
                tiles[0].column = 3;
            }
            accept
        }
    }

    GameBoardBackground { }

    Rectangle {
        for tile[i] in tiles: Tile {
            tile-data: tile;
            // x: tile.column * Style.tile-size + (tile.column + 1) * Style.margin;
            // y: tile.row * Style.tile-size + (tile.row + 1) * Style.margin;
        }
    }
}
