import { Button, VerticalBox, GridBox } from "std-widgets.slint";
import { TrainingWidget } from "training/training-widget.slint";
import { Plots, TrainingStats, Actions, UiTrainingState } from "globals.slint";
import { PlotSize } from "size.slint";

export { PlotSize }
export { Plots, TrainingStats, Actions, UiTrainingState }

export component AppWindow inherits Window {

    MenuBar {
        Menu {
            title: "file";
            MenuItem {
                title: "save model";
                activated => {
                    Actions.save-model();
                }
            }

            MenuItem {
                title: "load model";
                activated => {
                    Actions.load-model();
                }
            }

            MenuSeparator { }

            MenuItem {
                title: "quit";
                activated => {
                    Actions.quit();
                }
            }
        }
    }

    VerticalLayout {
        training-widget := TrainingWidget {
            state: TrainingStats.state;
            epoch: TrainingStats.epoch;
            epochs-per-second: TrainingStats.epochs-per-second;
            best-score: TrainingStats.best-score;
            best-tile: TrainingStats.best-tile;
            score-plot: Plots.score-plot;
            reward-plot: Plots.reward-plot;
            best-tile-plot: Plots.best-tile-plot;
            changed score-plot-size => {
                if (Plots.score-plot-size != self.score-plot-size) {
                    Plots.score-plot-size = self.score-plot-size;
                    Actions.plot-size-changed();
                }
            }
            changed reward-plot-size => {
                if (Plots.reward-plot-size != self.reward-plot-size) {
                    Plots.reward-plot-size = self.reward-plot-size;
                    Actions.plot-size-changed();
                }
            }
            changed best-tile-plot-size => {
                if (Plots.best-tile-plot-size != self.best-tile-plot-size) {
                    Plots.best-tile-plot-size = self.best-tile-plot-size;
                    Actions.plot-size-changed();
                }
            }
        }
    }
}
