import { Size } from "size.slint";

export enum UiTrainingState { idle, training }

export global Plots {
    in-out property <Size> plot-size;
    in property <image> score-plot;
    in property <image> reward-plot;
    in property <image> best-tile-plot;
}

export global TrainingStats {
    in property <UiTrainingState> state;
    in property <int> epoch;
    in property <float> epochs-per-second;
    in property <int> best-score;
    in property <int> best-tile;
    in property <int> recorded-states;
}

export global Actions {
    callback quit;
    callback load-model;
    callback save-model;
    callback plot-size-changed;
    callback start-training;
    callback pause-training;
}