import { PlotSize } from "size.slint";

export enum UiTrainingState { idle, training }
export enum UiPlotRangeType { all, last-epochs, custom }

export global Plots {
    in-out property <PlotSize> plots-area-size;
    callback plots-area-size-changed;
    in property <image> score-plot;
    in property <image> epoch-length-plot;
    in property <image> reward-plot;
    in property <image> best-tile-plot;
    in-out property <bool> log-scale;
    in-out property <UiPlotRangeType> range-type;
    in-out property <int> last-epochs;
    in-out property <int> custom-range-start;
    in-out property <int> custom-range-end;
    callback range-settings-changed;
}

export global UiTrainingStats {
    in property <UiTrainingState> state;
    in property <int> epoch;
    in property <int> epochs-per-second;
    in property <int> best-score;
    in property <int> best-tile;
    in property <int> recorded-states;
    in property <float> epsilon;
}

export global Actions {
    callback quit;
    callback load-model;
    callback save-model;
    callback load-session;
    callback save-session;
    callback start-training;
    callback pause-training;
}

export global Formatters {
    pure callback format-int(value: int) -> string;
}
